CREATE TABLE IF NOT EXISTS medicine (
	medicine_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	name text,
	disease text,
	price int
);

CREATE TABLE IF NOT EXISTS gender (
	gender_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	gender text
		NOT NULL
		UNIQUE
);

CREATE TABLE IF NOT EXISTS customer (
	customer_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	firstname text,
	lastname text,
	gender_id int
		NOT NULL
		REFERENCES gender
);

CREATE TABLE IF NOT EXISTS seller (
	seller_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	firstname text,
	lastname text,
	gender_id int
		NOT NULL
		REFERENCES gender
);

CREATE TABLE IF NOT EXISTS address (
	address_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	country text,
	city text,
	street text
);

CREATE TABLE IF NOT EXISTS pharmacy (
	pharmacy_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	name text,
	address_id int
		NOT NULL
		REFERENCES address
);

CREATE TABLE IF NOT EXISTS orders (
	order_id int
		GENERATED BY DEFAULT AS IDENTITY
		PRIMARY KEY,
	order_date date,
	medicine_id int
		NOT NULL
		REFERENCES medicine,
	customer_id int
		NOT NULL
		REFERENCES customer,
	seller_id int
		NOT NULL
		REFERENCES seller,
	pharmacy_id int
		NOT NULL
		REFERENCES pharmacy
);
